import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
  }

  class MyApp extends StatelessWidget {
    const MyApp({super.key});

      @override
        Widget build(BuildContext context) {
            return const MaterialApp(
                  debugShowCheckedModeBanner: false,
                        home: LoginPage(),
                            );
                              }
                              }

                              //////////////////// LOGIN PAGE ////////////////////

                              class LoginPage extends StatefulWidget {
                                const LoginPage({super.key});

                                  @override
                                    State<LoginPage> createState() => _LoginPageState();
                                    }

                                    class _LoginPageState extends State<LoginPage> {
                                      final usernameController = TextEditingController();
                                        final passwordController = TextEditingController();

                                          void login() {
                                              String username = usernameController.text;
                                                  String password = passwordController.text;

                                                      if (username == "admin" && password == "1234") {
                                                            Navigator.push(
                                                                    context,
                                                                            MaterialPageRoute(
                                                                                      builder: (context) => HomePage(username: username),
                                                                                              ),
                                                                                                    );
                                                                                                        } else {
                                                                                                              ScaffoldMessenger.of(context).showSnackBar(
                                                                                                                      const SnackBar(content: Text("Invalid Login")),
                                                                                                                            );
                                                                                                                                }
                                                                                                                                  }

                                                                                                                                    @override
                                                                                                                                      Widget build(BuildContext context) {
                                                                                                                                          return Scaffold(
                                                                                                                                                appBar: AppBar(
                                                                                                                                                        title: const Text("Owner Login"),
                                                                                                                                                                centerTitle: true,
                                                                                                                                                                      ),
                                                                                                                                                                            body: Padding(
                                                                                                                                                                                    padding: const EdgeInsets.all(20),
                                                                                                                                                                                            child: Column(
                                                                                                                                                                                                      children: [
                                                                                                                                                                                                                  const Align(
                                                                                                                                                                                                                                alignment: Alignment.centerLeft,
                                                                                                                                                                                                                                              child: Text("Enter your credentials"),
                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                      const SizedBox(height: 15),

                                                                                                                                                                                                                                                                                  TextField(
                                                                                                                                                                                                                                                                                                controller: usernameController,
                                                                                                                                                                                                                                                                                                              decoration: const InputDecoration(
                                                                                                                                                                                                                                                                                                                              labelText: "Username",
                                                                                                                                                                                                                                                                                                                                              border: OutlineInputBorder(),
                                                                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                                                                        ),

                                                                                                                                                                                                                                                                                                                                                                                    const SizedBox(height: 15),

                                                                                                                                                                                                                                                                                                                                                                                                TextField(
                                                                                                                                                                                                                                                                                                                                                                                                              controller: passwordController,
                                                                                                                                                                                                                                                                                                                                                                                                                            obscureText: true,
                                                                                                                                                                                                                                                                                                                                                                                                                                          decoration: const InputDecoration(
                                                                                                                                                                                                                                                                                                                                                                                                                                                          labelText: "Password",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          border: OutlineInputBorder(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const SizedBox(height: 25),

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            SizedBox(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          width: double.infinity,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        child: ElevatedButton(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onPressed: login,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        child: const Text("Login"),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                //////////////////// HOME PAGE ////////////////////

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                class HomePage extends StatefulWidget {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  final String username;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const HomePage({super.key, required this.username});

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      @override
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        State<HomePage> createState() => _HomePageState();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        class _HomePageState extends State<HomePage> {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          final memoryController = TextEditingController();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            final List<String> memories = [];

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              void addMemory() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  String text = memoryController.text.trim();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (text.isNotEmpty) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            setState(() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    memories.add(text);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            memoryController.clear();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          void deleteMemory(int index) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              setState(() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    memories.removeAt(index);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            void logout() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Navigator.pop(context);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    @override
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Widget build(BuildContext context) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          return Scaffold(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                appBar: AppBar(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        title: Text("Welcome ${widget.username}"),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                actions: [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          IconButton(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onPressed: logout,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  icon: const Icon(Icons.logout),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ),

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                body: Padding(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        padding: const EdgeInsets.all(16),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                child: Column(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          children: [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      TextField(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    controller: memoryController,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  decoration: const InputDecoration(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  hintText: "Write your memory...",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  border: OutlineInputBorder(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ),

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const SizedBox(height: 10),

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    SizedBox(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  width: double.infinity,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                child: ElevatedButton(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onPressed: addMemory,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                child: const Text("Save Memory"),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ),

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const SizedBox(height: 20),

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Expanded(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                child: memories.isEmpty
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ? const Center(child: Text("No memories yet"))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    : ListView.builder(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          itemCount: memories.length,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                itemBuilder: (context, index) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return Card(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  child: ListTile(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              title: Text(memories[index]),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          trailing: IconButton(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        icon: const Icon(Icons.delete),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onPressed: () => deleteMemory(index),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }