import 'package:flutter/material.dart';

import 'login_page.dart';

class WelcomePage extends StatelessWidget {
  const WelcomePage({super.key});

    @override
      Widget build(BuildContext context) {
          return Scaffold(
                body: Padding(
                        padding: const EdgeInsets.all(24),
                                child: Center(
                                          child: Column(
                                                      mainAxisAlignment: MainAxisAlignment.center,
                                                                  children: [
                                                                                const Icon(
                                                                                                Icons.favorite,
                                                                                                                size: 90,
                                                                                                                                color: Colors.pink,
                                                                                                                                              ),

                                                                                                                                                            const SizedBox(height: 25),

                                                                                                                                                                          const Text(
                                                                                                                                                                                          "Farewell Slam",
                                                                                                                                                                                                          style: TextStyle(
                                                                                                                                                                                                                            fontSize: 32,
                                                                                                                                                                                                                                              fontWeight: FontWeight.bold,
                                                                                                                                                                                                                                                              ),
                                                                                                                                                                                                                                                                            ),

                                                                                                                                                                                                                                                                                          const SizedBox(height: 15),

                                                                                                                                                                                                                                                                                                        const Text(
                                                                                                                                                                                                                                                                                                                        "Share memories and messages beautifully.",
                                                                                                                                                                                                                                                                                                                                        textAlign: TextAlign.center,
                                                                                                                                                                                                                                                                                                                                                        style: TextStyle(
                                                                                                                                                                                                                                                                                                                                                                          fontSize: 16,
                                                                                                                                                                                                                                                                                                                                                                                            color: Colors.grey,
                                                                                                                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                                                                                                                          ),

                                                                                                                                                                                                                                                                                                                                                                                                                                        const SizedBox(height: 40),

                                                                                                                                                                                                                                                                                                                                                                                                                                                      SizedBox(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      width: double.infinity,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      child: ElevatedButton(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onPressed: () {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Navigator.push(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  context,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        MaterialPageRoute(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                builder: (context) => const LoginPage(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              child: const Padding(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  padding: EdgeInsets.symmetric(vertical: 14),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      child: Text("Get Started"),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }